apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loginapp-certificate
spec:
  secretName: loginapp-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - zphighschool.shop

